server:
  port: 8084



spring:
  ldap:
    embedded:
      ldif: classpath:test-server.ldif
      base-dn:
      - dc=springframework,dc=org
      port: 8389

jwt:
  secret: secretkey123
#jks should be genrated properly  
user:
 jkspath: classpath:microservices.jks
 jkspwd: changeit
 jksalias: microservice
  
token:
  createexpiryTime: 10
  refreshexpiryTime: 10  
  